const COLORS = {
  EMPIRE_BLUE: '#4AA6F5',
};

const NEUTRALS = {
  BLACK: '#000',
  LIGHT_GRAY: '#F1EFEB',
  MED_LIGHT_GRAY: '#E8E5E1',
  LIGHT_BACKGROUND: '#FFF',
  OFF_WHITE_BACKGROUND: '#F8F8F8',
  LIGHT_TEXT: '#FFF',
  DARK_TEXT: '#282D2B',
  OFF_WHITE: '#F0EFEF',
  OFF_WHITE_BLUE: '#F1F9FF',
  WHITE: '#FFF',
};

export { COLORS, NEUTRALS };
